baseURL = "https://blog.sapus.us"
languageCode = "en-us"
title = "subzero"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  author = "subzero"
  description = "Place where to document my journey."
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto" # options: auto, light, dark
  SocialIcons = [
    { icon = "github", url = "https://github.com/yourusername" },
    { icon = "twitter", url = "https://twitter.com/yourusername" }
  ]
  ShareButtons = ["linkedin", "twitter"]
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]
  extendHead = "partials/extend_head.html"
  hamBurgerMenu = true

[params.search]
  enable = true
  fuseOpts = { isCaseSensitive = false, shouldSort = true, location = 0, distance = 1000, threshold = 0.4, minMatchCharLength = 0, keys = ["title", "permalink", "summary", "content"] }

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 3
 
 [[menu.main]]
    identifier = "sapet"
    name = "Sapet"
    url = "https://sapus.us"
    weight = 4

